# Generated by Django 4.1.7 on 2023-05-03 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название оборудования')),
            ],
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('doctor', 'Доктор'), ('patient', 'Пациент')], max_length=255, verbose_name='Тип пользователя')),
                ('middlename', models.CharField(default='Отчество', max_length=255, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('avatar', models.ImageField(default='../static/image/no_photography.png', upload_to='avatars', verbose_name='Аватарка')),
                ('anamnesis', models.TextField(blank=True, null=True, verbose_name='Анамнез')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='Диагноз')),
                ('address', models.CharField(blank=True, max_length=512, null=True, verbose_name='Адрес')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Biometr.human', verbose_name='Лечащий врач')),
                ('equipments', models.ManyToManyField(blank=True, null=True, to='Biometr.equipment', verbose_name='Оборудование')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id_equipment', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Biometr.equipment', verbose_name='Тип оборудования')),
                ('count', models.IntegerField(verbose_name='Количество')),
            ],
        ),
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Время измерения')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Biometr.equipment', verbose_name='Тип оборудования')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biometr.human', verbose_name='Пользователь')),
            ],
        ),
    ]
